class AppConfig:
    BG_COLOR = "#2D2D2D"
    FRAME_COLOR = "#373737"
    ACCENT_COLOR = "#4CAF50"
    TEXT_COLOR = "#FFFFFF"
    HOVER_COLOR = "#45a049"

    DEFAULT_DEPTH = 15
    DEFAULT_SCREENSHOT_DELAY = 0.4
    DEFAULT_MOVE_MODE = "drag"

    WINDOW_TITLE = "ChessPilot"
    WINDOW_WIDTH = 350
    WINDOW_HEIGHT = 380
